#ifndef ACCESS_H
#define ACCESS_H

#define IOCTL_SET_WINDOW_SAMPLES  0
#define IOCTL_SET_SIGNAL_ADDR	  1
#define IOCTL_SET_REF_SIGNAL_ADDR 6
#define IOCTL_SET_WINDOW	  3
#define IOCTL_SET_REF_WINDOW	  4
#define IOCTL_START_CALCULATION	  5
#define IOCTL_RESET_DEVICE	  7

#define MAX_WINDOW_SAMPLES	  64

#endif /* ACCESS_H */
