#ifndef ACCESS_H
#define ACCESS_H

#define IOCTL_SET_WINDOW_SIZE		 0
#define IOCTL_SET_SIGNAL_ADDR		 1
#define IOCTL_SET_WINDOW		 2
#define IOCTL_SET_LAST_WINDOW		 3

#define IOCTL_MODE_SET_REFERENCE_SIGNALS 1
#define IOCTL_MODE_SET_WINDOWS		 2

#define WINDOW_REGION_SIZE		 (4096)
#define REF_SIGNALS_REGION_SIZE		 (2048)
#endif
