#ifndef ACCESS_H
#define ACCESS_H

#define IOCTL_SET_MODE			 0
#define IOCTL_SET_WINDOW_SIZE		 1

#define IOCTL_MODE_SET_REFERENCE_SIGNALS 1
#define IOCTL_MODE_SET_WINDOWS		 2

#define WINDOW_REGION_SIZE		 (5 * 4096)
#define REF_SIGNALS_REGION_SIZE		 (4096)
#endif
