
#ifndef MSGDMA_H
#define MSGDMA_H

#define MSGDMA_CSR_STATUS_REG		    0x00
#define MSGDMA_CSR_CTRL_REG		    0x04
#define MSGDMA_CSR_FILL_LVL_REG		    0x08
#define MSGDMA_CSR_RESP_FILL_LVL_REG	    0x0C
#define MSGDMA_CSR_SEQ_NUM_REG		    0x10
#define MSGDMA_CSR_COMP_CONFIG1_REG	    0x14
#define MSGDMA_CSR_COMP_CONFIG2_REG	    0x18
#define MSGDMA_CSR_COMP_INFO_REG	    0x1C
#define MSGDMA_DESC_READ_ADDR_REG	    0x20
#define MSGDMA_DESC_WRITE_ADDR_REG	    0x24
#define MSGDMA_DESC_LEN_REG		    0x28
#define MSGDMA_DESC_CTRL_REG		    0x2C
#define MSGDMA_RESP_BYTES_TRANSFERRED_REG   0x30
#define MSGDMA_RESP_STATUS_REG		    0x34

#define MSGDMA_STATUS_IRQ		    (1 << 9)
#define MSGDMA_STATUS_STOPPED_EARLY_TERM    (1 << 8)
#define MSGDMA_STATUS_STOPPED_ON_ERR	    (1 << 7)
#define MSGDMA_STATUS_RESETTING		    (1 << 6)
#define MSGDMA_STATUS_STOPPED		    (1 << 5)
#define MSGDMA_STATUS_RESP_BUF_FULL	    (1 << 4)
#define MSGDMA_STATUS_RESP_BUF_EMPTY	    (1 << 3)
#define MSGDMA_STATUS_DESCR_BUF_FULL	    (1 << 2)
#define MSGDMA_STATUS_DESCR_BUF_EMTPY	    (1 << 1)
#define MSGDMA_STATUS_BUSY		    (1 << 0)

#define MSGDMA_CONTROL_STOP_DESCR	    (1 << 5)
#define MSGDMA_CONTROL_GLOBAL_INT_EN_MASK   (1 << 4)
#define MSGDMA_CONTROL_STOP_ON_EARLY_TERM   (1 << 3)
#define MSGDMA_CONTROL_STOP_ON_ERROR	    (1 << 2)
#define MSGDMA_CONTROL_RESET_DISPATCHER	    (1 << 1)
#define MSGDMA_CONTROL_STOP_DISPATCHER	    (1 << 0)

#define MSGDMA_DESC_CTRL_GO		    (1 << 31)
#define MSGDMA_DESC_CTRL_EARLY_DONE_EN	    (1 << 24)
#define MSGDMA_DESC_CTRL_TX_ERR_IRQ_EN	    (1 << 16)
#define MSGDMA_DESC_CTRL_EARLY_TERM_IRQ_EN  (1 << 15)
#define MSGDMA_DESC_CTRL_TX_COMPLETE_IRQ_EN (1 << 14)
#define MSGDMA_DESC_CTRL_END_ON_EOP	    (1 << 12)
#define MSGDMA_DESC_CTRL_PARK_WR	    (1 << 11)
#define MSGDMA_DESC_CTRL_PARK_RD	    (1 << 10)
#define MSGDMA_DESC_CTRL_GEN_EOP	    (1 << 9)
#define MSGDMA_DESC_CTRL_GEN_SOP	    (1 << 8)

#endif /*MSGDMA_H*/
